### ISSUE TITLE
Forum Profile Editing (by Darren)

### ISSUE THREAD

**Issue by Bhumika-P** [rijulaggarwal16/wp-ssquiz#4]
When a student replies on a thread or creates one, they can click on their name that is linked to their forum profile. They will see an edit button and if they click edit, they can change their name and set a nickname and display name. The First and Last name changes the very name of the account of the user. Which we disabled on the main profile. That needs to be disabled.

Also when they set a nickname for the forum and set it as their display name, the portal will use that name in the auto grading emails. Either the display name set needs to be disabled or detached from the user account so it does not affect the main account but only the forum.

**Comment by rijulaggarwal16** [comment]
Unrelated
