### ISSUE TITLE
Portal Sent Exam Completion Email to Early

### ISSUE THREAD

**Issue by Bhumika-P** [rijulaggarwal16/wp-ssquiz#7]
I completed an exam today for real and during the process i was checking to see if the answers of his exam were correct. I found that some answers were not right and had to correct them. I Saved and Exited the exam and change the answer to the correct one in SSQUIZ and went back to my exam to continue on with my studying. However, during that, i received an email stating i completed an exam with 77% and 31 or 32 questions completed. I do not know how to reproduce the issue but i do have a concern with our website bugging out and sending the completion email when they save and exit.

**Comment by rijulaggarwal16** [comment]
Do you receive the email every time you save and exit? You need to dig around a little more in-terms of how to reproduce it. Also, the plugin assumes questions will be set before you start taking them. It does not support changes after you start taking them and might produce very unexpected results.
