### ISSUE TITLE
Error in retaking exam

### ISSUE THREAD

**Issue by Bhumika-P** [rijulaggarwal16/wp-ssquiz#9]
Reproduction steps:
1) student fails a course
2) student takes the exam again (two_chance)
3) student clicks save and exit
4) it gives the screen of " successfully saved "
5) student goes on main page of portal
5) student goes back to exam again to continue
6) and student clicks on the exam
7) gives the "successfully saved screen"
8) sent an email as exam completed

**Comment by rijulaggarwal16** [comment]
Fixed in recent commit
